name: Deploy to Crates.io
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  test:
    name: Build/Test
    uses: travisbaars/actions/rust/std-test.yml@main

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: test
    steps:
      - uses: actions/checkout@v4

      - run: cargo publish --token ${{ secrets.token }}
        env:
          CRATES_TOKEN: ${{ secrets.token }}
