name: Standard Test
on:
  workflow_call:
    inputs:
      target:
        required: true

env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
