name: Integration
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Test (standard)
    steps:
      - uses: travisbaars/actions-rs/.github/workflows/std-test.yml@main
