name: Integration
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: travisbaars/actions-rs/.github/workflows/std-test.yml@main

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: travisbaars/actions-rs/.github/workflows/format.yml@main